# Gemini API Key from Google AI Studio
GEMINI_API_KEY = "AIzaSyDMvyo4Jrrq-6Ygej8Mq5nOiDnLzBvmx4k"

# Google Custom Search API Key
GOOGLE_API_KEY = "AIzaSyCxjO7ccpf0fp0Am_qRKQQCv3XpQoNW3Zo"

# Custom Search Engine ID
CUSTOM_SEARCH_ENGINE_ID = "33f28abf3d6a5451b"